# -*- coding: utf-8 -*-
"""rag-sesh2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U8-F5TjacMh7Neli6AOCTwp9RR597ijc

### Chunking Strategy

We use **clause-level semantic chunking built from sentences**.

The text is first split into sentences, and then semantically related sentences are grouped into chunks representing a single concept (e.g., termination, liability, confidentiality).

This approach improves retrieval by:

* keeping chunks **meaningful and self-contained**
* reducing **irrelevant context**
* aligning chunks with **real-world concepts**

It works especially well for structured documents like legal or technical content, where each clause can be retrieved independently.
"""

!pip install sentence-transformers -q

from sentence_transformers import SentenceTransformer, util
import numpy as np
import textwrap, re
import matplotlib.pyplot as plt

model = SentenceTransformer('all-MiniLM-L6-v2')
print("Model loaded ✓")

paragraph = """Software licensing agreements typically contain several critical provisions that govern the relationship between the licensor and the licensee. The grant of license clause REF-2024-7B defines the scope of permitted use for Version 4.1.2 of the software, including whether the license is exclusive or non-exclusive, the geographic territory covered, and the specific editions included. Termination clauses outline the conditions under which either party may end the agreement, with common triggers including material breach, insolvency, or failure to pay royalties within the specified cure period of thirty days as defined under clause MSA-9942. Intellectual property ownership sections clarify that the licensor retains all rights to the underlying code, and that any modifications or derivative works created by the licensee during the term remain the property of the licensor unless explicitly stated otherwise in a written amendment signed by both parties. Liability limitations under error code LIC-ERR-403 cap the total damages recoverable by either party to the fees paid in the preceding twelve months, excluding cases of gross negligence or willful misconduct. Confidentiality obligations require both parties to protect non-public technical documentation, pricing structures, and customer data using at minimum the same degree of care applied to their own proprietary information."""

# ── Cell 4: Split into sentences ─────────────────────────────
# Regex-based splitter that respects abbreviations like "v4.1.2"
def split_sentences(text):
    # Split on ". " only when followed by a capital letter
    sentences = re.split(r'(?<=[.!?])\s+(?=[A-Z])', text.strip())
    return [s.strip() for s in sentences if s.strip()]

sentences = split_sentences(paragraph)
print(f"Total sentences found: {len(sentences)}\n")
for i, s in enumerate(sentences):
    print(f"  S{i}: {textwrap.shorten(s, width=90)}")

# ── Cell 5: Embed sentences & compute adjacent cosine similarity
sentence_embeddings = model.encode(sentences, convert_to_tensor=True)

# Similarity between each consecutive sentence pair
adjacent_scores = []
for i in range(len(sentences) - 1):
    score = float(util.cos_sim(sentence_embeddings[i], sentence_embeddings[i+1]))
    adjacent_scores.append(score)
    print(f"  S{i} → S{i+1} similarity: {score:.4f}")

# ── Cell 6: Detect chunk boundaries ──────────────────────────
# A boundary exists where similarity DROPS below the threshold.
# Lower score = topic has shifted = start a new chunk.

THRESHOLD = 0.40   # tune this: lower = more chunks, higher = fewer

boundaries = [0]   # chunk always starts at sentence 0
for i, score in enumerate(adjacent_scores):
    if score < THRESHOLD:
        boundaries.append(i + 1)   # next sentence starts a new chunk
boundaries.append(len(sentences))  # sentinel

print(f"\nThreshold : {THRESHOLD}")
print(f"Boundaries detected at sentence indices: {boundaries}")

# ── Cell 7: Build chunks from boundaries ─────────────────────
chunks = []
for idx in range(len(boundaries) - 1):
    start = boundaries[idx]
    end   = boundaries[idx + 1]
    chunk_sentences = sentences[start:end]
    chunk_text = " ".join(chunk_sentences)
    chunks.append({
        "id"        : f"chunk_{idx+1:02d}",
        "sentences" : list(range(start, end)),
        "text"      : chunk_text,
    })

print(f"\nTotal chunks created: {len(chunks)}\n")
print("═" * 65)
for c in chunks:
    print(f"[{c['id']}]  sentences {c['sentences']}")
    print(textwrap.fill(c['text'], width=65,
                        initial_indent="  ", subsequent_indent="  "))
    print()

# ── Cell 8: Visualise — where did the splits happen? ─────────
fig, ax = plt.subplots(figsize=(10, 3.5))

x = range(len(adjacent_scores))
ax.plot(x, adjacent_scores, marker='o', color='#3B8BD4',
        linewidth=1.8, markersize=6, label='Adjacent sentence similarity')
ax.axhline(THRESHOLD, color='#E85D30', linewidth=1.2,
           linestyle='--', label=f'Threshold = {THRESHOLD}')

# Shade the split points
for b in boundaries[1:-1]:
    ax.axvline(b - 0.5, color='#E85D30', linewidth=1,
               linestyle=':', alpha=0.7)
    ax.text(b - 0.5, max(adjacent_scores) + 0.02,
            f'split', fontsize=7, color='#E85D30', ha='center')

ax.set_xticks(list(x))
ax.set_xticklabels([f"S{i}→S{i+1}" for i in x], fontsize=8, rotation=30)
ax.set_ylabel("Cosine similarity")
ax.set_title("Semantic similarity between adjacent sentences\n(dips below threshold = clause boundary)")
ax.legend(fontsize=9)
ax.set_ylim(0, 1.1)
plt.tight_layout()
plt.show()

# ── Cell 9: RAG retrieval ─────────────────────────────────────
chunk_texts      = [c["text"] for c in chunks]
chunk_embeddings = model.encode(chunk_texts, convert_to_tensor=True)

def retrieve(query: str, top_k: int = 2):
    q_emb  = model.encode(query, convert_to_tensor=True)
    scores = util.cos_sim(q_emb, chunk_embeddings)[0]
    ranked = sorted(zip(scores.tolist(), chunks),
                    key=lambda x: x[0], reverse=True)
    print(f'\nQuery : "{query}"')
    print("─" * 65)
    for rank, (score, chunk) in enumerate(ranked[:top_k], 1):
        print(f"  Rank {rank} | Score: {score:.4f} | [{chunk['id']}]  sentences {chunk['sentences']}")
        print(textwrap.fill(chunk['text'], width=65,
                            initial_indent="    ", subsequent_indent="    "))
        print()

retrieve("What is the cure period if royalties are not paid?")
retrieve("Who owns derivative works made by the licensee?")
retrieve("What is the cap on recoverable damages?")
retrieve("How should confidential pricing data be handled?")
retrieve("Is the software license exclusive or non-exclusive?")

!pip install sentence-transformers rank-bm25 -q

from sentence_transformers import SentenceTransformer, util
from rank_bm25 import BM25Okapi
import numpy as np
import textwrap, re

model = SentenceTransformer('all-MiniLM-L6-v2')
print("Model loaded ✓")

# ── Cell 3: Chunks from Topic 2 (threshold=0.40 result) ──────
chunks = [
    {
        "id": "chunk_01",
        "clause": "Scope & License Grant",
        "text": (
            "Software licensing agreements typically contain several critical "
            "provisions that govern the relationship between the licensor and "
            "the licensee. The grant of license clause REF-2024-7B defines the "
            "scope of permitted use for Version 4.1.2 of the software, including "
            "whether the license is exclusive or non-exclusive, the geographic "
            "territory covered, and the specific editions included."
        ),
    },
    {
        "id": "chunk_02",
        "clause": "Termination Conditions",
        "text": (
            "Termination clauses outline the conditions under which either party "
            "may end the agreement, with common triggers including material breach, "
            "insolvency, or failure to pay royalties within the specified cure "
            "period of thirty days as defined under clause MSA-9942."
        ),
    },
    {
        "id": "chunk_03",
        "clause": "Intellectual Property Ownership",
        "text": (
            "Intellectual property ownership sections clarify that the licensor "
            "retains all rights to the underlying code, and that any modifications "
            "or derivative works created by the licensee during the term remain "
            "the property of the licensor unless explicitly stated otherwise in a "
            "written amendment signed by both parties."
        ),
    },
    {
        "id": "chunk_04",
        "clause": "Liability Limitations",
        "text": (
            "Liability limitations under error code LIC-ERR-403 cap the total "
            "damages recoverable by either party to the fees paid in the preceding "
            "twelve months, excluding cases of gross negligence or willful misconduct."
        ),
    },
    {
        "id": "chunk_05",
        "clause": "Confidentiality Obligations",
        "text": (
            "Confidentiality obligations require both parties to protect non-public "
            "technical documentation, pricing structures, and customer data using "
            "at minimum the same degree of care applied to their own proprietary "
            "information."
        ),
    },
]

# BM25 works on token overlap — tokenise by lowercasing + splitting
def tokenize(text):
    return re.sub(r'[^a-z0-9\s]', '', text.lower()).split()

tokenized_corpus = [tokenize(c["text"]) for c in chunks]
bm25 = BM25Okapi(tokenized_corpus)
print(f"BM25 index built over {len(chunks)} chunks ✓")

chunk_texts      = [c["text"] for c in chunks]
chunk_embeddings = model.encode(chunk_texts, convert_to_tensor=True)
print(f"Semantic embeddings shape: {chunk_embeddings.shape} ✓")


# ── Cell 6: Search functions ──────────────────────────────────
def bm25_search(query, top_k=2):
    tokens = tokenize(query)
    scores = bm25.get_scores(tokens)
    ranked = sorted(zip(scores, chunks), key=lambda x: x[0], reverse=True)
    return ranked[:top_k]

def semantic_search(query, top_k=2):
    q_emb  = model.encode(query, convert_to_tensor=True)
    scores = util.cos_sim(q_emb, chunk_embeddings)[0].tolist()
    ranked = sorted(zip(scores, chunks), key=lambda x: x[0], reverse=True)
    return ranked[:top_k]

queries = [
    {
        "q": "What happens if someone doesn't pay on time?",
        "note": "PARAPHRASE — uses 'doesn't pay on time' not 'royalties/cure period'",
    },
    {
        "q": "clause MSA-9942",
        "note": "EXACT TOKEN — a specific clause reference that appears verbatim",
    },
    {
        "q": "What are the consequences if I copy and change the software?",
        "note": "CONCEPTUAL — no shared words with IP chunk; tests pure understanding",
    },
]

DIVIDER = "═" * 68

for item in queries:
    query = item["q"]
    note  = item["note"]

    bm25_results     = bm25_search(query)
    semantic_results = semantic_search(query)

    print(f"\n{DIVIDER}")
    print(f"Query : \"{query}\"")
    print(f"Note  : {note}")
    print(DIVIDER)

    print(f"\n{'BM25 (keyword)':^34} | {'Semantic (embedding)':^34}")
    print(f"{'-'*34}-+-{'-'*34}")

    for i in range(2):
        bm_score, bm_chunk   = bm25_results[i]
        sem_score, sem_chunk = semantic_results[i]

        bm_label  = f"[{bm_chunk['id']}] {bm_chunk['clause']}"
        sem_label = f"[{sem_chunk['id']}] {sem_chunk['clause']}"

        print(f"  Rank {i+1}: {bm_label:<28} |   Rank {i+1}: {sem_label}")
        print(f"  Score: {bm_score:<6.4f}                      |   Score: {sem_score:.4f}")
        print()

    # Flag agreement or disagreement
    bm_top  = bm25_results[0][1]["id"]
    sem_top = semantic_results[0][1]["id"]
    if bm_top == sem_top:
        print(f"  AGREE   — both return {bm_top} at rank 1")
    else:
        print(f"  DISAGREE — BM25={bm_top}, Semantic={sem_top}  <-- interesting!")

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

chunk_labels = [f"{c['id']}\n{c['clause'][:14]}" for c in chunks]
x = np.arange(len(chunks))
width = 0.35
fig, axes = plt.subplots(1, 3, figsize=(16, 4), sharey=False)

colors = {'bm25': '#3B8BD4', 'sem': '#E85D30'}

for ax, item in zip(axes, queries):
    query = item["q"]

    bm_scores  = bm25.get_scores(tokenize(query))
    q_emb      = model.encode(query, convert_to_tensor=True)
    sem_scores = util.cos_sim(q_emb, chunk_embeddings)[0].tolist()

    # Normalise BM25 to 0-1 for visual comparison
    bm_max = max(bm_scores) if max(bm_scores) > 0 else 1
    bm_norm = [s / bm_max for s in bm_scores]

    bars1 = ax.bar(x - width/2, bm_norm,  width, color=colors['bm25'],  alpha=0.85, label='BM25 (norm.)')
    bars2 = ax.bar(x + width/2, sem_scores, width, color=colors['sem'], alpha=0.85, label='Semantic')

    ax.set_xticks(x)
    ax.set_xticklabels(chunk_labels, fontsize=7)
    ax.set_ylim(0, 1.15)
    ax.set_title(f'"{query[:38]}..."' if len(query) > 38 else f'"{query}"',
                 fontsize=8, wrap=True)
    ax.set_ylabel("Score (BM25 normalised)")
    ax.legend(fontsize=7)

    # highlight rank-1 for each method
    bm_winner  = int(np.argmax(bm_norm))
    sem_winner = int(np.argmax(sem_scores))
    ax.get_xticklabels()[bm_winner].set_color(colors['bm25'])
    ax.get_xticklabels()[sem_winner].set_color(colors['sem'])

plt.suptitle("BM25 vs Semantic — score distribution per query\n(x-label colour = rank-1 winner for that method)",
             fontsize=10)
plt.tight_layout()
plt.show()

