# -*- coding: utf-8 -*-
"""rag_sesh1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G767bdpBvm3jbrsd5gqIYENEoEGXP20m
"""

!pip install sentence-transformers -q

from sentence_transformers import SentenceTransformer, util
import torch

# all-MiniLM-L6-v2 is small but strong — good for semantic tasks
model = SentenceTransformer('all-MiniLM-L6-v2')
print("Model loaded ✓")

pairs = [
    {
        "label": "1 · Negation trap",
        "strategy": "Opposite meaning, near-identical words",
        "hypothesis": "HIGH score despite opposite meaning",
        "s1": "The patient survived the surgery.",
        "s2": "The patient did not survive the surgery.",
    },
    {
        "label": "2 · False friends",
        "strategy": "Shared keywords, different topic",
        "hypothesis": "HIGH score, but one is about animals, one about food",
        "s1": "I absolutely love dogs.",
        "s2": "I absolutely love hot dogs.",
    },
    {
        "label": "3 · Same meaning, different words",
        "strategy": "Synonymous sentences, zero shared words",
        "hypothesis": "LOW score despite identical meaning",
        "s1": "The automobile malfunctioned on the motorway.",
        "s2": "The car broke down on the highway.",
    },
    {
        "label": "4 · Sentiment flip via framing",
        "strategy": "Structurally identical, polar sentiment",
        "hypothesis": "HIGH score despite one being praise, one being insult",
        "s1": "What a brilliant idea!",
        "s2": "What a terrible idea!",
    },
    {
        "label": "5 · Idiom vs literal",
        "strategy": "Same phrase, completely different meaning",
        "hypothesis": "LOW score — model should separate idiom from literal",
        "s1": "He kicked the bucket last night.",       # idiom: he died
        "s2": "He kicked the bucket across the yard.",  # literal: physical kick
    },
    {
        "label": "6 · Sarcasm trap",
        "strategy": "Sarcastic sentence vs sincere antonym",
        "hypothesis": "HIGH score — sarcasm and its literal opposite share structure",
        "s1": "Oh great, another Monday morning.",      # sarcastic: dreads Monday
        "s2": "Oh no, another Monday morning.",         # sincere: also dreads Monday
    },
    {
        "label": "7 · Topic drift via proper noun",
        "strategy": "Same sentence skeleton, wildly different domain",
        "hypothesis": "HIGH score — model anchors on structure, misses domain shift",
        "s1": "Apple is planning to release a new product next year.",   # tech company
        "s2": "Amazon is planning to release a new product next year.",  # different company
    },
    {
        "label": "8 · Formal vs slang paraphrase",
        "strategy": "Identical meaning, register so different embeddings may diverge",
        "hypothesis": "LOW score despite meaning the same thing",
        "s1": "I am experiencing significant financial difficulties.",
        "s2": "I'm totally broke, bro.",
    },
    {
        "label": "9 · Numeric flip",
        "strategy": "One word change that inverts factual truth",
        "hypothesis": "HIGH score — model ignores the number that changes everything",
        "s1": "World War II ended in 1945.",
        "s2": "World War II ended in 1965.",
    },
    {
        "label": "10 · False cause vs true cause",
        "strategy": "Same event, opposite causal direction",
        "hypothesis": "HIGH score — embeddings capture topic, not causality",
        "s1": "Exercise improves mental health.",
        "s2": "Mental health improves exercise.",
    },
]

def score_pair(s1, s2):
    emb = model.encode([s1, s2], convert_to_tensor=True)
    return float(util.cos_sim(emb[0], emb[1]))

print(f"{'─'*70}")
for p in pairs:
    score = score_pair(p["s1"], p["s2"])

    # verdict: did we fool it?
    fooled = (
        (p["hypothesis"].startswith("HIGH") and score > 0.75) or
        (p["hypothesis"].startswith("LOW")  and score < 0.50)
    )
    verdict = "✅ FOOLED" if fooled else "❌ NOT FOOLED"

    print(f"\n{p['label']}")
    print(f"  Strategy : {p['strategy']}")
    print(f"  S1       : {p['s1']}")
    print(f"  S2       : {p['s2']}")
    print(f"  Score    : {score:.4f}   ({verdict})")
    print(f"  Expected : {p['hypothesis']}")
    print(f"{'─'*70}")

import matplotlib.pyplot as plt

labels = [p["label"] for p in pairs]
scores = [score_pair(p["s1"], p["s2"]) for p in pairs]
colors = ['#E85D30' if s > 0.75 else '#3B8BD4' for s in scores]

fig, ax = plt.subplots(figsize=(10, 4))
bars = ax.barh(labels, scores, color=colors, height=0.55)
ax.axvline(0.75, color='#E85D30', lw=1, ls='--', alpha=0.5, label='High threshold (0.75)')
ax.axvline(0.50, color='#3B8BD4', lw=1, ls='--', alpha=0.5, label='Low threshold (0.50)')
for bar, s in zip(bars, scores):
    ax.text(s + 0.01, bar.get_y() + bar.get_height()/2,
            f'{s:.3f}', va='center', fontsize=9)
ax.set_xlim(0, 1.05)
ax.set_xlabel("Cosine similarity")
ax.set_title("Can we fool the similarity score?")
ax.legend(fontsize=8)
plt.tight_layout()
plt.show()

